#########################################
#            玩家權限表                   #
#     treasure-bag.<permission>         #
#########################################

MAX_SLOT:
  VIP: 45
  VIP2: 90
  VIP3: 135
  VIP4: 180
