#########################################
#            玩家權限表                   #
#     treasure-bag.<permission>         #
#########################################

MAX_SLOT:
  DEFAULT: 45
  VIP: 90
  VIP2: 135
  VIP3: 180
  VIP4: 225
